name: Pull Request Checks

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 3.1.102

            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'

            - name: Check Building
              run: |
                  npm install
                  cd site/AntBlazor.Docs.ClientApp/wwwroot
                  rm index.html
                  cp -r gh-pages/* gh-pages/.nojekyll ./
                  rm -r gh-pages
                  cd ../../../
                  dotnet build
                  dotnet publish -c Release -o tmp
