name: Pull Request Checks

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 3.1.201

            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'

            - name: Check Building ⚙
              run: |
                  npm install
                  cp -rf scripts/gh-pages/* scripts/gh-pages/.nojekyll scripts/gh-pages/.spa ./site/AntBlazor.Docs.Wasm/wwwroot
                  dotnet build
                  dotnet publish -c Release -o cargo
